public class main {
	static class Product {
		String id = "";
		String PName = "";
		int Price = 0;

		// void SetData(String a, String b, int c) throws ProductException {
		// if (c < 0) {
		// throw new ProductException();
		// }
		//
		// id = a;
		// PName = b;
		// Price = c;
		// }
		void SetData(String id, String PName, int Price) throws ProductException {
			if (Price < 0) {
				throw new ProductException();
			}

			this.id = id;
			this.PName = PName;
			this.Price = Price;
		}
	}

	static class ProductException extends Exception {
		//預設,沒有要覆寫,就不必寫建構子,
	}

	public static void main(String args[]) {
		Product product = new Product();
		try {
			product.SetData("123", "123", -1);
		} catch (ProductException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("拋出錯誤!");
		}
	}
}